### ISSUE TITLE
Can not login via google

### ISSUE THREAD

**Issue by s9gf4ult** [snoyberg/haskellers#17]
When I am trying to login via google it redirects me to https://support.google.com/accounts/answer/6206245?p=openid&rd=1

**Comment by snoyberg** [comment]
I announced that this was coming a year ago:

http://www.haskellers.com/news/16

I should remove the logo from the login page now.

**Comment by qrilka** [comment]
Any chance to login into lost account?

**Comment by snoyberg** [comment]
If you added an email address to the account, log in via Persona.

**Comment by qrilka** [comment]
Thanks, that works
