### ISSUE TITLE
Style makes job descriptions hard to read

### ISSUE THREAD

**Issue by danse** [snoyberg/haskellers#20]
Like in here for example http://www.haskellers.com/jobs/100

**Comment by snoyberg** [comment]
PRs certainly welcome

**Comment by danse** [comment]
Any idea about how did this happen? I would not like to change some style without knowing the context. I guess that the theme was working initially

**Comment by danse** [comment]
Background and foreground colour are set consistently for `body.find-job`, but this seems overridden by the `style` attribute on the descriptions `span` elements. Maybe these are set via Javascript or similar

**Comment by danse** [comment]
I am a bit lost, i cannot find any `.julius` file responsible for this

**Comment by danse** [comment]
Maybe the problem could be [inlined HTML?](https://github.com/snoyberg/haskellers/blob/da7c4e9036d23f813e734ef971c971ce9c53202e/tests/templates/job.hamlet#L34-L35)

**Comment by snoyberg** [comment]
I've honestly not looked at this code in years, and possibly never (there was quite some overhaul to the CSS at some point). But I think we just need a background-color: white on #desc.

**Comment by danse** [comment]
Style rules seem consistent, but [the Hamlet code i pasted above](https://github.com/snoyberg/haskellers/blob/da7c4e9036d23f813e734ef971c971ce9c53202e/templates/job.hamlet#L39-L40) seems to include raw HTML when that is available. I think that the included HTML is carrying some style rules specifically set in the element's attributes, and those rules do not play well with the rest of the style. If this is the problem, i think that a good compromise could be to strip all `style` attributes from the inlined HTML

**Comment by snoyberg** [comment]
We don't want to do that, job posting should be allowed safe stylings like color changes. I'm fairly certain just setting the background on the div will have the right result, I'll test shortly.

**Comment by snoyberg** [comment]
Looks to me like it's fixed on the live site.

**Comment by danse** [comment]
Yes, it is readable now on the live site, but what if a custom HTML in the future has a white or light colour? Also, the style looks uglier now. The original colour and font was nicer. In my opinion, stripping `style` attributes had been a better solution, anyway thanks for fixing this and making those posts readable again!

**Comment by danse** [comment]
[Here](http://www.haskellers.com/jobs/98), for example, the light style applied to the link makes it unreadable

**Comment by snoyberg** [comment]
If you'd like a change, please send a PR. There's no way to address every single possible coloring that submitters may provide.

**Comment by danse** [comment]
I will spend some time trying to implement a filter which removes `style` from inlined markup, so that custom markup can be accepted while keeping a nice, readable style. I am meeting some inconsistencies in the documentation, so i will likely issue several small pull requests adjusting things here and there. I am trying to use Stack in order to install and run this
