### ISSUE TITLE
Some configuration file is missing

### ISSUE THREAD

**Issue by danse** [snoyberg/haskellers#22]
When trying to run a development instance via `stack exec -- yesod devel`, after some successful operations the server fails and it prints the following lines:
```
devel.hs: InvalidYaml (Just (YamlException "Yaml file not found: config/db/aws"))
Exit code: ExitFailure 1
```
Indeed, i do not have any `config/db/aws.yml` file. Probably something changed in the installation process, also because i cannot find the files referred at point 6 of the installation instructions. How to set up a development instance?

**Comment by snoyberg** [comment]
I've added a dummy aws file to the repo.
