### ISSUE TITLE
What is the status of tests here and which strategy would you suggest to restore their functionality?

### ISSUE THREAD

**Issue by danse** [snoyberg/haskellers#24]
I am afraid that tests here are not working. When i run `stack test`, it fails with the following error:
```
tests/Import.hs:13:2: lexical error at character 'i'
```
Which is caused by what i think is a conditional compilation directive [here](https://github.com/snoyberg/haskellers/blob/d84a2d6647a997f945382204921ca04b4e0fb5f7/tests/Import.hs#L13). If i comment that directive out, i see a very long list of errors due to missing dependencies for tests, like in:
```
/Users/francesco/repos/haskellers/tests/Settings.hs:28:8:
    Could not find module ‘Text.Hamlet’
    It is a member of the hidden package ‘shakespeare-2.0.5’.
    Perhaps you need to add ‘shakespeare’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
```
Besides this, it seems that the content of `tests` mirrors the content of the root folder. Maybe the only true test there is `tests/HomeTest.hs`. So i am not sure whether this works or ever worked. To me it seems like there was a plan to do something with all these copied files, but then the plan was abandoned.

So, where to go from here? Maybe it would be a good idea to just keep `HomeTest` and delete all the rest, leaving room for new tests to start from scratch. I am afraid that some problem might still persist though, due to the dependencies missing in the test section of the cabal file. Hopefully there is some goodness coming from Slack which can help us with this.

**Comment by snoyberg** [comment]
The test suite has not been used in a while, I'm fine with any move you
want to take on it.
