### ISSUE TITLE
What is purpose of ‘entities’ file?

### ISSUE THREAD

**Issue by mrkkrp** [snoyberg/haskellers#28]
I'm having hard time understanding purpose of `entities` file. You have `config/models` and that's what is used in `Models.hs`, however it looks like `entities`:

1. …is never used in source code according to `grep`.

2. …is older version of `config/models`(?)

Could we just remove `entities` file to avoid confusion?

**Comment by snoyberg** [comment]
It can probably be removed, want to try sending a PR?
