### ISSUE TITLE
Remove confusing attributes in 'config/models' file

### ISSUE THREAD

**Issue by mrkkrp** [snoyberg/haskellers#30]
Please see second half of this discussion for background:

https://github.com/yesodweb/yesod/issues/1098

In short, this file:

https://github.com/snoyberg/haskellers/blob/master/config/models

is very confusing because it contains a lot of obsolete entity attributes, so @gregwebs asked me to open this issue. Is it possible to remove all the confusing attributes like `Ask`, `Desc`, `In`, `Gt`, and others?

Since Haskellers site is sort of example (at least I use it as a reference) for Yesod developers, it would be very desirable to keep it understandable. I, for instance, have read most part of Yesod book, but when I started to learn how Haskellers works, I got strong impression that Yesod has a lot of esoteric, undocumented features not explained in Yesod book or documentation, mainly because of this file.

**Comment by snoyberg** [comment]
Yes, there's no problem, if you send a PR I'll be happy to merge it.

**Comment by mrkkrp** [comment]
One more thing, does `toFormField=maybeEmailField` have any meaning? Should it be removed as well?

**Comment by snoyberg** [comment]
I don't believe it does anything either, but compiling without it should
reveal that quickly.
