### ISSUE TITLE
Recaptcha doesn't work anymore

### ISSUE THREAD

**Issue by frontsideair** [snoyberg/haskellers#43]
![screenshot 2018-06-20 11 44 38](https://user-images.githubusercontent.com/868283/41647544-5ccc14b2-747f-11e8-8a80-e325f6702d7d.png)

I can work on this.

**Comment by snoyberg** [comment]
Thanks for the report, and the help would definitely be appreciated! Let me know if you have any questions.

**Comment by frontsideair** [comment]
Looks like `mailhide` is discontinued with [no replacement in v2](https://github.com/google/recaptcha/issues/41#issuecomment-104373437). I'm checking the [alternatives](https://alternativeto.net/software/recaptcha-mailhide/). Both work similarly and neither is accessible to blind users, unfortunately.

**Comment by snoyberg** [comment]
@frontsideair just pinging, are you still interested in working on this?

**Comment by frontsideair** [comment]
I still have some tabs open about it, looks like I went into yak-shaving mode to build a mailhide replacement for a more general use.

What do you think about the alternatives I mentioned? I think inaccessible captcha is not cool. OTOH people don't care as much as they did about posting plain email addresses on the internet, probably due to better spam filters.

I'd like to work on this but I don't want to force a solution, unless it's as good as the previous one.

**Comment by snoyberg** [comment]
While accessibility would be great, right now we have data that was intended to be protected which is freely available for scraping. Given that, I'd be OK with adding a non-accessible captcha system, even though I don't like it.

Basically: at this point, I'd be OK taking just about any solution, and we can talk about refinements later. If you're interested in creating a new alternative to MailHide, I think that would be a great project and a great demonstration of Haskell, and I'd definitely be interested in hearing about it :)

**Comment by frontsideair** [comment]
5 days and no response from Spamty. I'll try my chance with Scrim by asking the dev for instructions to use the API. If that doesn't work out, it's either roll-my-own-mailhide or don't hide at all.

**Comment by isovector** [comment]
What's the status on this?

**Comment by snoyberg** [comment]
I'm taking a stab at a Mailhide replacement myself to try and unblock this. If anyone has something shorter-term to fix this, let me know.

**Comment by snoyberg** [comment]
I've pushed a change to production which uses my new site, sortasecret.com, to hide email addresses. It's really simple, and I'll probably improve it over time, but it seems sufficient for our needs right now.
