### ISSUE TITLE
Shut down the site?

### ISSUE THREAD

**Issue by snoyberg** [snoyberg/haskellers#47]
Blog post with the proposal: https://www.snoyman.com/blog/2021/03/shutting-down-haskellers/. Please add comments, and/or use the voting emojis on this description to express your position.

**Comment by blackheaven** [comment]
I can understand the drawbacks of maintaining it, but, while the Discourse would be great for discussions, it will lack the "geolocalisation" part.

That is how I discovered, few months ago, that there were a company doing Haskell in my area, and we planned to setup a meetup group.

Anyway, thank you for allowing us to connect.

**Comment by juhp** [comment]
What about packdeps.haskellers.com ?

**Comment by snoyberg** [comment]
> What about https://packdeps.haskellers.com ?

No intention on my part to change it at all.

**Comment by isovector** [comment]
I use Haskellers all the time when traveling; it's a cool way to meet up with interesting people no matter where I am. I for one would be sad to see it go.

**Comment by tfausak** [comment]
👍🏻 from me. I signed up back in the day but I don't think I've ever actually used the site.

**Comment by sajith** [comment]
Haskellers.com is not super critical (to me anyway), but it is fun and pretty unique.  It is not as formal as the other venues.  I learned a bunch of things about Yesod from reading its sources.  It would be nice if someone else could maintain it (and improve it their way!), if Michael doesn't want to do that anymore.

What if Haskellers.com could become something like [advogato](https://web.archive.org/web/20170715120119/http://advogato.org/), but for Haskellers?  It could be a fun little community project.  I'd imagine that aspiring Haskellers can learn a lot from hacking on something like it.

**Comment by snoyberg** [comment]
I really hadn't considered the geolocation aspect of Haskellers being so valuable to people. That really changes my calculation here a lot. If people are using it, I'm in no rush to take down the site. But perhaps slimming down the feature set a bit and including more community resources would be a Good Thing.

> It would be nice if someone else could maintain it

In this case, if people have thoughts on improvements, I'm definitely open to them. Besides some user assistance from time to time, I don't have much in the way of a maintenance burden from the site.

**Comment by snoyberg** [comment]
Given that there seem to be enough people interested in the geolocation features, I'm going to leave Haskellers unchanged for now. Thanks to everyone for their input. If anyone is interested in taking a stab at some changes to Haskellers, such as providing some community resources _in addition_ to the geolocation feature, let me know (ideally in a new issue proposing the change). As usual, PRs welcome!
